name: release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types:
      - labeled

jobs:
  release:
    if: github.event.action != 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nekottyo-org/auto-tag-action-example/.github/workflows/release.yaml@main

  release-check:
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nekottyo-org/auto-tag-action-example/.github/workflows/release-check.yaml@main
