name: release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types:
      - labeled

jobs:
  release:
    uses: nekottyo-orgs/auto-tag-action-example/.github/workflows/release.yaml@main

  release-check:
    uses: nekottyo-orgs/auto-tag-action-example/.github/workflows/release-check.yaml@main
