name: release
on:
  workflow_dispatch:
    inputs:
      bump_level:
        description: 'Bump level'
        required: true
        default: 'patch'
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'

jobs:
  release:
    uses: nekottyo-orgs/auto-tag-action-example/.github/workflows/release.yaml@main
    with:
      bump_level: ${{ github.event.inputs.bump_level }}
