name: release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false
        default: ""


jobs:
  service-release:
    uses: nekottyo-orgs/auto-tag-action-example/.github/workflows/service-release.yaml@main
    with:
      version: ${{ github.event.inputs.version }}
