name: service release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the release'
        type: string
        required: false
        default: ""


jobs:
  service-release:
    uses: nekottyo-orgs/auto-tag-action-example/.github/workflows/service-release.yaml@main
    with:
      tag: ${{ github.event.inputs.tag }}
